/*
 * File: app/store/MyXmlStore.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.store.MyXmlStore', {
    extend: 'Ext.data.Store',

    requires: [
        'MyApp.model.RSSModel'
    ],

    config: {
        autoLoad: true,
        autoSync: true,
        model: 'MyApp.model.RSSModel',
        storeId: 'MyXmlStore',
        sorters: {
            property: 'word',
            root: 'data'
        },
        grouper: {
            groupFn: function(item) {
                return item.get('word')[0].toUpperCase();


            }
        },
        proxy: {
            type: 'ajax',
            url: 'http://tecmo.webfactional.com/gre/xml/words.xml',
            reader: {
                type: 'xml',
                rootProperty: 'vocabulary',
                record: 'word'
            }
        }
    }
});