/*
 * File: app/view/MyContainer1.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.MyContainer1', {
    extend: 'Ext.Container',
    alias: 'widget.mycontainer11',

    config: {
        id: 'myContainer1',
        ui: '',
        layout: {
            type: 'fit'
        },
        items: [
            {
                xtype: 'container',
                docked: 'top',
                height: '10%',
                html: 'Today is a great day :)',
                id: 'myContainer2',
                left: '12.5%',
                style: 'background-color:white',
                top: '7.5%',
                width: '75%'
            },
            {
                xtype: 'button',
                handler: function(button, event) {
                    container3 = Ext.getCmp('myContainer3');
                    container3.setHtml('<font size="4"><i>'+definition+'</i></font>');

                },
                centered: false,
                left: '27.5%',
                top: '25%',
                ui: 'forward',
                width: '45%',
                iconAlign: 'center',
                text: 'I\'m feeling lucky'
            },
            {
                xtype: 'container',
                docked: 'bottom',
                height: '35%',
                id: 'myContainer3',
                left: '12.5%',
                style: 'background-color:white',
                top: '40%',
                width: '75%'
            },
            {
                xtype: 'toolbar',
                docked: 'top',
                title: 'Time to play',
                items: [
                    {
                        xtype: 'button',
                        handler: function(button, event) {
                            Ext.getCmp('tabPanel').setActiveItem(Ext.getCmp('myContainer'));
                        },
                        text: 'Back'
                    }
                ]
            },
            {
                xtype: 'button',
                handler: function(button, event) {
                    store = Ext.getStore('MyXmlStore');
                    var size = store.getCount();
                    var rand = Math.random(); 
                    var id = Math.round(rand*size);
                    container = Ext.getCmp('myContainer2');
                    container.setHtml('<font size="5"><b><center>'+store.getAt(id).get('word')+'</center></b></font>');
                    container3 = Ext.getCmp('myContainer3');
                    container3.setHtml('');
                    definition = store.getAt(id).get('definition');
                },
                left: '30%',
                top: '80%',
                width: '40%',
                iconCls: 'favorites',
                text: 'New Word'
            }
        ]
    }

});